#!/usr/bin/env bash

__run_textlint() {
    local docker_image="testthedocs/textlint"
    local host_src_volume="${PWD}"
    local container_dest_volume="/work"

    docker run --volume="${host_src_volume}:${container_dest_volume}" --workdir="${container_dest_volume}" --rm "${docker_image}" $@
}

__run_textlint $@
